global_frame: map
rolling_window: true

update_frequency: 10.0
publish_frequency: 10.0
transform_tolerance: 0.5

width: 1.5
height: 1.5

cost_scaling_factor: 1.0

plugins:
 - {name: obstacles,                 type: "costmap_2d::ObstacleLayer"}
 - {name: inflation,                 type: "costmap_2d::InflationLayer"}