TebLocalPlannerROS:
    odom_topic: /odom
    map_frame: map

    # Trajectory

    # teb_autosize: True
    # dt_ref: 0.4
    # dt_hysteresis: 0.1
    # max_samples: 500
    # global_plan_overwrite_orientation: True
    allow_init_with_backwards_motion: False
    # max_global_plan_lookahead_dist: -1
    # global_plan_viapoint_sep: -1
    # global_plan_prune_distance: 1
    # exact_arc_length: False
    # feasibility_check_no_poses: 2
    # publish_feedback: False

    # Robot
         
    wheelbase: 0.25
    # cmd_angle_instead_rotvel: True

    max_vel_x: 0.2
    max_vel_x_backwards: 0.1

    max_vel_theta: 0.43
    acc_lim_x: 0.3
    acc_lim_theta: 0.1
    # Just to avoid too high turn
    min_turning_radius: 0.3 # wheelbase / tan(max_steer)
    footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
        type: "polygon"
        # radius: 0.3 # for type "circular"
        # line_start: [-0.16, 0.0] # for type "line"
        # line_end: [0.16, 0.0] # for type "line"
        # front_offset: 0.2 # for type "two_circles"
        # front_radius: 0.2 # for type "two_circles"
        # rear_offset: 0.2 # for type "two_circles"
        # rear_radius: 0.2 # for type "two_circles"
        vertices: [ [0.15, 0.15], [-0.15, 0.15], [-0.15, -0.15], [0.15, -0.15] ] # for type "polygon"

    # GoalTolerance

    xy_goal_tolerance: 0.5
    yaw_goal_tolerance: 0.8
    free_goal_vel: False
    complete_global_plan: True

    # Obstacles
    min_obstacle_dist: 0.3

    include_costmap_obstacles: True
    costmap_obstacles_behind_robot_dist: 0.3
    obstacle_poses_affected: 5 #15